version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: easysplit-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: easysplit
      POSTGRES_PASSWORD: easysplit
      POSTGRES_DB: easysplit
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
